---
- name: installing wildfly(JBOSS)
  become: yes
  hosts: all
  var:
    java: openjdk-11-jdk
    jboss_group: wildfly
    jboss_user: wildfly
    jboss_url: https://download.jboss.org/wildfly/22.0.1.Final/wildfly-22.0.1.Final.tar.gz
    jboss_url_dest:  /tmp/
  tasks:
    - name: installing java
      ansible.builtin.apt:
        name: "{{ java }}"
        update_cache: yes
        state: present
    - name: downloading jboss url
      ansible.builtin.get_url:
        url: "{{ jboss_url }}"
        dest: "{{ jboss_url_dest }}"
        mode: '777'
    - name: archiving the tar file
      ansible.builtin.unarchive:
        src: /tmp/wildfly-22.0.1.Final.tar.gz
        dest: /tmp/
        remote_src: yes
    - name: Ensure group "somegroup" exists
      ansible.builtin.group:
        name: "{{ jboss_group }}"
        state: present
    - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: "{{ jboss_user }}"
        comment: wildfly
        uid: 2050
        group: wildfly
    - name: Create Folder
      file: 
        path: /etc/wildfly
        owner: wildfly
        group: wildfly
        mode: '0777'
        state: directory
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.conf
        dest: /etc/wildfly/
        owner: wildfly
        group: wildfly
        mode: '0777'
        remote_src: yes
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /opt/wildfly/docs/contrib/scripts/systemd/launch.sh
        dest: /opt/wildfly/bin/
        owner: wildfly
        group: wildfly
        mode: '0777'
        remote_src: yes
    - name: copying files
      ansible.builtin.copy:
        src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.service
        dest: /etc/systemd/system/
        owner: wildfly
        group: wildfly
        remote_src: yes
        mode: '0777'    
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /opt/wildfly/bin/
        owner: wildfly  
        group: wildfly
        mode: '0777'
    - name: ensure the apache service is running and enabled
      ansible.builtin.systemd:
        name: wildfly.service
        state: restarted
        daemon_reload: yes
    - name: Start a service with systemd
      systemd:
        name: wildfly.service
        state: started
    - name: Enable nginx service
      systemd:
        name: wildfly.service
        enabled: true
        masked: no